# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Oswald Analytics
tagline:          A blog on academia, statistics, statistics and life.
description:      A blog on academia, statistics, statistics and life.
url:               http://oswaldanalytics.github.io 
baseurl:          /

author:
  name:           'Christopher Oswald'
  url:             http://oswaldanalytics.github.io 

paginate:         5


github:
  repo:           https://github.com/oswaldanalytics
