# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Oswald
tagline:          Temp
description:      tempU
url:               http://oswaldanalytics.github.io 
baseurl:          /

author:
  name:           'Christopher Oswald'
  url:             http://oswaldanalytics.github.io 

paginate:         5


github:
  repo:           https://github.com/oswaldanalytics
