# Dependencies
markdown: kramdown
kramdown:
  input: GFM
highlighter:      rouge

# Setup
title:            Oswald Analytics
tagline:          A blog on academia, statistics, research and life.
description:      A blog on academia, statistics, research and life.
url:               http://oswaldanalytics.github.io 
baseurl:          /

author:
  name:           'Christopher Oswald'
  url:             http://oswaldanalytics.github.io 

paginate:         10

pages_list:       
  About: '/about'
  Archive: '/archive'
  CV: '/cv'
  Feed: '/atom.xml'

github:
  repo:           https://github.com/oswaldanalytics
